---
#
# Disable selinux
#
- name: temporarily disable selinux
  action: shell echo 0 > /selinux/enforce
- name: disable selinux completely
  action: shell /bin/sed -i 's|SELINUX=enforcing|SELINUX=disabled|' /etc/sysconfig/selinux
#
# Configure a custom repository at packages.serverascode.com/mrepo
# that has the vcl, vcl-web, and vcl-managementnode RPMs
#
- name: install the serverascode centos 6 yum repo file 
  action: copy src=files/serverascode-centos6.repo dest=/etc/yum.repos.d/serverascode-centos6.repo owner=root group=root mode=0644
  notify:
    - refresh yum cache
- name: make yum cache (could take a while)
  action: shell /usr/bin/yum clean all; /usr/bin/yum makecache
#
# Install rpmforge and epel repositories
#
# XXX perhaps repo rpms should be variables XXX
- name: install rpmforge repository
  action: yum pkg=rpmforge-release state=installed
  notify:
    - refresh yum cache
- name: install epel repository
  action: yum pkg=epel-release state=installed
  notify:
    - refresh yum cache
- name: make yum cache again (could take a while)
  action: shell /usr/bin/yum clean all; /usr/bin/yum makecache
#
# uninstall dhclient if it's installed
# 
- name: uninstall dhclient if it's installed
  action: yum pkg=dhclient state=removed

# NOTE: This is the normal version
# Make sure vcl-* are installed
#
- name: make sure vcl is installed
  action: yum pkg=vcl state=installed
  only_if: '$is_normal_version'
- name: make sure vcl-web is installed
  action: yum pkg=vcl-web state=installed
  only_if: '$is_normal_version'
- name: make sure vcl-managementnode is installed
  action: yum pkg=vcl-managementnode state=installed
  only_if: '$is_normal_version'

# NOTE: This is the cybera version...
# Make sure vcl-cybera-* are installed
#
- name: make sure vcl-cybera is installed
  action: yum pkg=vcl-cybera state=installed
  only_if: '$is_cybera_version'
- name: make sure vcl-cybera-web is installed
  action: yum pkg=vcl-cybera-web state=installed
  only_if: '$is_cybera_version'
- name: make sure vcl-cybera-managementnode is installed
  action: yum pkg=vcl-cybera-managementnode state=installed
  only_if: '$is_cybera_version'

#
# Iptables
#
- name: install iptables rules
  action: copy src=files/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=0775
  notify:
    - restart iptables
- name: ensure iptables is running 
  action: service name=iptables state=running
- name: chkconfig iptables on
  action: command /sbin/chkconfig iptables on
#
# Apache
#
- name: ensure apache is installed
  action: yum pkg=httpd state=installed
- name: make sure apache is running
  action: service name=httpd state=running
- name: copy over the vcl.conf file
  action: copy src=files/vcl.conf dest=/etc/httpd/conf.d/vcl.conf owner=root group=root mode=0644
  notify:
    - restart apache
#
# Database
#
- name: ensure mysqld is installed
  action: yum pkg=mysql-server state=installed
- name: make sure mysql is running  
  action: service name=mysqld state=running
#
# VCL web GUI configuration
#
- name: copy over conf.php template
  action: template src=templates/conf.j2 dest=/usr/share/vcl-web/.ht-inc/conf.php owner=root group=apache mode=0640
- name: copy over secrets.php template
  action: template src=templates/secrets.j2 dest=/usr/share/vcl-web/.ht-inc/secrets.php
#
# vcld configuration file
#
- name: copy over vcld.conf template
  action: template src=templates/vcld.j2 dest=/etc/vcl/vcld.conf owner=root group=root mode=0640
