---
# For the purposes of this example we'll just turn off iptables, bad sysadmin!
- name: turn off iptables service
  action: service name=iptables state=stopped
- name: chkconfig iptables off
  action: command /sbin/chkconfig iptables off
#
# Apache
#
- name: ensure latest apache is installed
  action: yum pkg=httpd state=latest
- name: make sure apache is running
  action: service name=httpd state=running
- name: copy over the vcl.conf file
  action: copy src=files/vcl.conf dest=/etc/httpd/conf.d/vcl.conf owner=root group=root mode=0644
#
# VCL RPMs
#
- name: make sure vcl is installed
  action: yum pkg=vcl state=installed
- name: make sure vcl-web is installed
  action: yum pkg=vcl-web state=installed
- name: make sure vcl-managementnode is installed
  action: yum pkg=vcl-managementnode state=installed
#
# Database
#
- name: ensure latest mysqld is installed
  action: yum pkg=mysql-server state=latest
- name: make sure mysql is running  
  action: service name=mysqld state=running
#
# VCL web GUI configuration
#
- name: copy over conf.php
  action: copy src=files/conf.php dest=/usr/share/vcl-web/.ht-inc/conf.php owner=root group=apache mode=0640
- name: copy over secrets.php template
  action: template src=templates/secrets.j2 dest=/usr/share/vcl-web/.ht-inc/secrets.php
