---

- name: update apt
  action: shell apt-get update

- name: install required software defined networking packages
  action: apt pkg=$item state=installed
  with_items:
  #  - auto-install
    - openvswitch-datapath-source 
    - bridge-utils
    - module-assistant  
   # - openvswitch-datapath
    - openvswitch-brcompat
    - openvswitch-common
    - openvswitch-switch
    - linux-headers-3.2.0-23-generic
    - git
    - python-zdaemon

- name: check if the openvswitch-switch module is already built and installed
  action: shell lsmod | grep openvswitch_mod
  ignore_errors: True
  register: openvswitch_module_installed
  # openvswitch_module_installed should be empty if there is no module with that name

- name: build openvswitch-switch module
  action: shell module-assistant -q auto-install openvswitch-datapath
  when_unset: $openvswitch_module_installed

- name: configure /etc/default/openvswitch-switch
  action: copy src=files/openvswitch-switch dest=/etc/default/openvswitch-switch
  notify: restart ovs

# TODO -- make br-int a variable
- name: see if br-int is already running
  action: shell brctl show | grep br-int
  register: bridge_up
  ignore_errors: True

- name: add a bridge-utils
  action: shell ovs-vsctl add-br br-int
  when_unset: $bridge_up

# TODO -- pull this info from ansible
- name: add a physical interface to the virtual bridge-utils
  action: shell ovs-vsctl add-port br-int eth1; ifconfig eth1 0; ifconfig br-int 192.168.33.10 netmask 255.255.255.0
  when_unset: $bridge_up

- name: add a default route
  action: shell route add default gw 192.168.33.1 br-int; route del default gw 10.0.2.2 eth0
  when_unset: $bridge_up

- name: check if we have already cloned the pox repository
  action: file path=/usr/local/src/pox state=directory
  register: pox_installed

# Only bring in pox if it's not already there
- name: clone pox repository
  action: shell cd /usr/local/src; git clone http://github.com/noxrepo/pox
  only_if: '${pox_installed.changed}'

# maybe don't need to do this with zdaemon, it'll say it's already running..
#- name: check is pox is running
#  action: shell pgrep -f pox > /dev/null; echo $?
#  ignore_errors: True
#  register: pox_running

- name: start pox if it isn't running already
  action: shell zdaemon -p 'python /usr/local/src/pox/pox.py --no-cli forwarding.l2_learning' -d start
#  only_if: "$pox_running > 0"

#- name: attached openswtich to the controller
#  action: shell ovs-vsctl set-controller br-int tcp:192.168.1.208:6633