#
# Make sure admin users on each node exist
#

- name: ensure admin users are present
  action: user name=$item state=present password=$password group=$item groups=sudo,adm createhome=yes shell=/bin/bash
  with_items: $ubuntu_os_admin_user

# ssh keys in authorized keys file...
- name: copy over ssh key for authorized keys file
  action: authorized_key user=$item state=present key='$PIPE(./get_keys.sh $item)'
  with_items: $ubuntu_os_admin_user

