#
# Install a nova compute node
# 

- name: apt-get update
  action: command /usr/bin/apt-get update

# XXX This page http://docs.openstack.org/trunk/openstack-compute/install/content/installing-the-cloud-controller.html
# shows a couple more pacakges, such as nova-vncproxy?? XXX
- name: install various compute node nova packages
  action: apt pkg=$item state=installed
  with_items:
    - nova-common
    - nova-compute
    - bridge-utils
    - guestmount
    - nova-volume

- name: if qemu install nova-compute-qemu
  action: apt pkg=nova-compute-qemu state=installed
  only_if: '$is_hypervisor_qemu'

- name: if kvm install nova-compute-kvm
  action: apt pkg=nova-compute-kvm state=installed
  only_if: '$is_hypervisor_kvm'

#
# Nova config
#
- name: copy nova.conf template over
  action: template src=templates/nova.j2 dest=/etc/nova/nova.conf

- name: copy over nova's api-paste.ini template
  action: template src=templates/api-paste.j2 dest=/etc/nova/api-paste.ini

- name: stop all nova services
  action: command service $item stop
  ignore_errors: True
  with_items:
    - nova-compute
    - nova-volume

- name: start all nova services
  action: command service $item start
  with_items:
    - nova-compute
    - nova-volume

# XXX Not sure if this is needed on a compute node XXX
#- name: sync nova-manage's db
#  action: command nova-manage db sync

- name: set permissions on /etc/nova
  action: command chown -R nova:nova /etc/nova

- name: stop all nova services again
  action: command service $item stop
  ignore_errors: True
  with_items:
    - nova-compute
    - nova-volume

- name: start all nova services again
  action: command service $item start
  with_items:
    - nova-compute
    - nova-volume

- name: make sure nova-compute and volume will start on reboot
  action: service name=$item state=started enabled=yes
  with_items:
    - nova-compute
    - nova-volume