- name: apt-get update
  action: command /usr/bin/apt-get update

# http://docs.openstack.org/trunk/openstack-compute/install/content/installing-the-cloud-controller.html
# - novnc won't install with nova-vncproxy
- name: install various nova cloud controller packages
  action: apt pkg=$item state=installed
  with_items:
    - nova-api
    - nova-cert
    - nova-common
    - nova-doc
    - nova-network
    - nova-objectstore
    - nova-scheduler
    - nova-consoleauth
    - nova-vncproxy
#    - novnc
    - python-nova
    - python-novaclient
    - bridge-utils

#
# Nova config
# 
- name: copy nova.conf template over
  action: template src=templates/nova.j2 dest=/etc/nova/nova.conf

- name: copy over nova's api-paste.ini template
  action: template src=templates/api-paste.j2 dest=/etc/nova/api-paste.ini

#
# Services
#
- name: stop all nova services
  action: command service $item stop
  ignore_errors: True
  with_items:
    - libvirt-bin
    - nova-network
    - nova-cert
    - nova-api
    - nova-objectstore
    - nova-scheduler
    - nova-consoleauth

- name: start all nova services
  action: command service $item start
  with_items:
    - libvirt-bin
    - nova-network
    - nova-cert
    - nova-api
    - nova-objectstore
    - nova-scheduler
    - nova-consoleauth

# XXX NOT IDEMPOTENT XXX
- name: sync nova-manage's db
  action: command nova-manage db sync

- name: create nova networks
  action: shell /usr/bin/nova-manage network create --num_networks=100 --label=private --fixed_range_v4=10.0.100.0/8 || true

- name: set permissions on /etc/nova
  action: command chown -R nova:nova /etc/nova

- name: stop all nova services again
  action: command service $item stop
  ignore_errors: True
  with_items:
    - libvirt-bin
    - nova-network
    - nova-cert
    - nova-api
    - nova-objectstore
    - nova-scheduler
    - nova-consoleauth

- name: start all nova services again
  action: command service $item start
  with_items:
    - libvirt-bin
    - nova-network
    - nova-cert
    - nova-api
    - nova-objectstore
    - nova-scheduler
    - nova-consoleauth

- name: add root's keypair to nova
  action: shell /bin/bash -c 'source /home/${ubuntu_os_admin_user}/defaulttenantrc; nova keypair-add --pub_key /home/${ubuntu_os_admin_user}/.ssh/id_dsa.pub ${default_tenant}'

