 # http://www.hastexo.com/resources/docs/installing-openstack-essex-20121-ubuntu-1204-precise-pangolin
- name: apt-get update
  action: command /usr/bin/apt-get update
- name: install various packages
  action: apt pkg=$item state=installed
  with_items:
    - tgt
    - open-iscsi
    - open-iscsi-utils
    - bridge-utils
    - rabbitmq-server
    - memcached
    - python-memcache
    - kvm
    - libvirt-bin
    - mysql-server
    - python-mysqldb