- name: apt-get update
  action: command /usr/bin/apt-get update
- name: install various glance packages
  action: apt pkg=$item state=installed
  with_items:
    - glance 
    - glance-api 
    - glance-client 
    - glance-common 
    - glance-registry 
    - python-glance

#- name: configure glance admin_tenant_name
#  action: command sed -i 's|admin_tenant_name = %SERVICE_TENANT_NAME%|admin_tenant_name = service|g' /etc/glance/glance-api-paste.ini

#- name: configure glance admin_user
#  action: command sed -i 's|admin_user = %SERVICE_USER%|admin_user = glance|g' /etc/glance/glance-api-paste.ini

#- name: configure glance admin_password
#  action: command sed -i 's|admin_password = %SERVICE_PASSWORD%|admin_password = ${admin_password}|g' /etc/glance/glance-api-paste.ini

# Note that this is sql_connection 
- name: configure glances's db connection
  action: command sed -i 's|sql_connection = sqlite:////var/lib/glance/glance.sqlite|sql_connection = mysql://glancedbadmin:${mysql_user_pw}@${ansible_eth0.ipv4.address}/glance|g' /etc/glance/glance-registry.conf

# could do with items here
- name: copy over glance-api-paste.ini template
  action: template src=templates/glance-api-paste.j2 dest=/etc/glance/glance-api-paste.ini

- name: copy over glance-regsitry-paste.ini template
  action: template src=templates/glance-registry-paste.j2 dest=/etc/glance/glance-registry-paste.ini

# XXX FIXME ME - not idempotent XXX
- name: tell glance registry and api to use keystone for authentication
  action: shell echo "[paste_deploy] \nflavor = keystone" >> /etc/glance/glance-${item}.conf
  with_items:
    - registry
    - api

# XXX FIXME ME - not idempotent XXX
- name: syncronize glance db
  action: shell glance-manage version_control 0; glance-manage db_sync

# glance-api has no status so can't do service
- name: restart glance-api
  action: command service glance-api restart

- name: restart glance-registry
  action: command service glance-registry restart

# use bash -c because source is a builtin...might be a better way...
- name: try running glance index
  action: shell /bin/bash -c 'source /home/vagrant/openstackrc.sh; glance index'

- name: try to import img
  ignore_errors: true
  action: shell /bin/bash -c 'source /home/vagrant/openstackrc.sh; glance add name="Ubuntu 12.04 cloudimg amd64" is_public=true container_format=ovf disk_format=qcow2 < /vagrant/ansible_playbooks/openstack_essex/files/ubuntu-12.04-server-cloudimg-amd64-disk1.img'
