- name: apt-get update
  action: command /usr/bin/apt-get update
  tags:
    - packages

- name: install various keystone packages
  action: apt pkg=$item state=installed
  with_items:
    - python-mysqldb
    - keystone 
    - python-keystone 
    - python-keystoneclient
  tags:
    - packages

# http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-keystone.html
- name: ensure sqlite keystone database is deleted
  action: file dest=/var/lib/keystone/keystone.db state=absent
  tags:
    - database

# Might need to set dbadmin name in vars/main.yml
- name: configure keystone's db connection
  action: command sed -i 's|connection = sqlite:////var/lib/keystone/keystone.db|connection = mysql://keystonedbadmin:${mysql_user_pw}@${controller_ip}/keystone|g' /etc/keystone/keystone.conf
  tags:
    - database

- name: configure keystone's admin token
  action: command sed -i 's|admin_token = ADMIN|admin_token = ${keystone_admin_token}|g' /etc/keystone/keystone.conf
  tags:
    - configuration

- name: restart keystone
  action: shell service keystone stop; service keystone start
  tags:
    - service

#***********************************#
# ENDPOINTS.SH and KEYSTONE_DATA.SH #
#***********************************#

# XXX NOT IDEMPOTENT XXX
- name: init keystone db
  action: command /usr/bin/keystone-manage db_sync
  tags:
    - database

- name: copy over keystone_data.sh script from template
  action: template src=templates/keystone_data.j2 dest=/usr/local/bin/keystone_data.sh mode=0755
  tags:
    - database
    - configuration

# XXX NOT IDEMPOTENT XXX
- name: run keystone_data.sh
  action: command /usr/local/bin/keystone_data.sh
  tags:
    - database
    - configuration

- name: copy endpoints.sh file
  action: copy src=files/endpoints.sh dest=/usr/local/bin/endpoints.sh mode=0755
  tags:
    - database
    - configuration


# XXX Should remove swift stuff XXX
- name: setup endpoints via endpoints.sh
  action: shell /usr/local/bin/endpoints.sh -m ${controller_ip} -u keystonedbadmin -D keystone -p ${mysql_user_pw} -K ${controller_ip} -R RegionOne -E "http://127.0.0.1:35357/v2.0" -T ${keystone_admin_token}
  tags:
    - database
    - configuration

#************************************#
# /ENDPOINTS.SH and KEYSTONE_DATA.SH #
#************************************#

- name: restart keystone (again)
  action: shell service keystone stop; service keystone start
  tags:
    - service

- name: copy over openstackrc.sh to ${ubuntu_os_admin_user}'s home dir
  action: template src=templates/openstackrc.j2 dest=/home/${ubuntu_os_admin_user}/openstackrc mode=0640 owner=${ubuntu_os_admin_user} group=${ubuntu_os_admin_user}
  tags:
    - configuration

- name: copy over defaulttenantrc to ${ubuntu_os_admin_user}'s home dir
  action: template src=templates/defaulttenantrc.j2 dest=/home/${ubuntu_os_admin_user}/defaulttenantrc mode=0640 owner=${ubuntu_os_admin_user} group=${ubuntu_os_admin_user}
  tags:
    - configuration

# use bash -c because source is a builtin...might be a better way...
- name: test keystone
  action: shell /bin/bash -c 'source /home/${ubuntu_os_admin_user}/openstackrc; keystone user-list'
  tags:
    - test
