- name: apt-get update
  action: command /usr/bin/apt-get update

- name: install various glance packages
  action: apt pkg=$item state=installed
  with_items:
    - nova-api
    - nova-cert
    - nova-common
    - nova-compute
    - nova-compute-kvm
    - nova-doc
    - nova-network
    - nova-objectstore
    - nova-scheduler
    - nova-volume
    - nova-consoleauth
    - novnc
    - python-nova
    - python-novaclient

- name: copy nova.conf template over
  action: template src=templates/nova.j2 dest=/etc/nova/nova.conf

- name: copy over nova's api-paste.ini template
  action: template src=templates/api-paste.j2 dest=/etc/nova/api-paste.ini

- name: stop all nova services
  action: command service $item stop
  ignore_errors: True
  with_items:
    - libvirt-bin
    - nova-network
    - nova-compute
    - nova-cert
    - nova-api
    - nova-objectstore
    - nova-scheduler
    - novnc
    - nova-consoleauth
#    - nova-volume

- name: start all nova services
  action: command service $item start
  with_items:
    - libvirt-bin
    - nova-network
    - nova-compute
    - nova-cert
    - nova-api
    - nova-objectstore
    - nova-scheduler
    - novnc
    - nova-consoleauth
#    - nova-volume

- name: sync nova-manage's db
  action: command nova-manage db sync

# Note brige_interfaces is backwards from instructions
- name: create nova networks
  action: command nova-manage network create private --fixed_range_v4=192.168.22.32/27 --num_networks=1 --bridge=br100 --bridge_interface=eth0 --network_size=32

- name: set permissions on /etc/nova
  action: command chown -R nova:nova /etc/nova

- name: stop all nova services again
  action: command service $item stop
  ignore_errors: True
  with_items:
    - libvirt-bin
    - nova-network
    - nova-compute
    - nova-cert
    - nova-api
    - nova-objectstore
    - nova-scheduler
    - novnc
    - nova-consoleauth
#    - nova-volume

- name: start all nova services again
  action: command service $item start
  with_items:
    - libvirt-bin
    - nova-network
    - nova-compute
    - nova-cert
    - nova-api
    - nova-objectstore
    - nova-scheduler
    - novnc
    - nova-consoleauth
#    - nova-volume
