---
- hosts: openstack
  user: root
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/setup.yml
    - include: tasks/keystone.yml
    - include: tasks/glance.yml
    - include: tasks/cc_nova.yml
