---
- hosts: 127.0.0.1
  user: root
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/controller_packages.yml
    - include: tasks/ntp.yml
    - include: tasks/mysql.yml
    - include: tasks/keystone.yml
    - include: tasks/glance.yml
    - include: tasks/controller_nova.yml
