---
- hosts: openstack
  user: root
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/mysql.yml
    - include: tasks/keystone.yml
    - include: tasks/glance.yml
    - include: tasks/controller_nova.yml
