---
#
# Todo:

- name: install required pxe boot packages
  action: apt pkg=$item state=installed
  with_items:
    #- tftpd
    - debmirror
    - dnsmasq
    - apache2
    - apt-cacher-ng

- name: copy over dnsmasq.conf template
  action: template src=templates/dnsmasq.j2 dest=/etc/dnsmasq.conf

- name: ensure apt-cacher-ng is running
  action: service name=apt-cacher-ng state=started

# oops, could grab netboot from cd...
# could this lead to a mismatch of kernel/installer...???
- name: grab netboot files for Ubuntu 12.04
  action: get_url url=http://archive.ubuntu.com/ubuntu/dists/precise/main/installer-amd64/current/images/netboot/netboot.tar.gz dest=/var/tmp/netboot.tar.gz

- name: create /tftp directory
  action: file dest=/tftp state=directory owner=root group=root mode=0755

- name: untar netboot.tar.gz into /tftp
  action: command tar -zxvf /var/tmp/netboot.tar.gz -C /tftp

- name: copy over syslinux.cfg
  action: copy src=files/syslinux.cfg dest=/tftp/ubuntu-installer/amd64/boot-screens/syslinux.cfg

# Doesn't seem to work with service
- name: restart dnsmasq
  action: command service dnsmasq restart

- name: ensure apache2 is running
  action: service name=apache2 state=running

- name: copy over various preseeding files
  action: copy src=files/$item dest=/var/www/$item
  with_items:
    - cc.preseed
    - node.preseed
    - early_command_node_phy2
    - early_command_cc_phy2
    - setup.tar
    - network-config.sh
